name: Build AppImage

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: debian:13

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Yarn
        run: corepack enable yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build ${{ matrix.arch }}
        run: yarn make --arch ${{ matrix.arch }}

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: AppImage-linux-${{ matrix.arch }}
          path: out/**/*.AppImage
