name: Build AppImage
on:
  workflow_dispatch:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Yarn
        run: corepack enable yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Install AppImage dependencies
        run: sudo apt-get install -y libfuse2
      - name: Build
        run: yarn make --arch x64
      - name: Patch AppImage icon
        run: bash scripts/patch-appimage.sh
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: AppImage-linux-x64
          path: out/**/*.AppImage